Recommended photos table was add
fiiraz/dsapi pull request #22
Opened 2020-03-14 23:23 UTC by emineayik

Recommended photos table did added

2020-03-14 23:42 UTC, aykutyurtmen commented on src/main/java/com/daimontech/dsapi/photos/model/RecommendedPhotos.java
> +
please reformat code(ctrl+alt+L)

2020-03-14 23:43 UTC, aykutyurtmen commented on src/main/java/com/daimontech/dsapi/photos/model/RecommendedPhotos.java
> +import com.daimontech.dsapi.company.model.companyAbout;
delete unnecessety library.

2020-03-14 23:44 UTC, aykutyurtmen commented on src/main/java/com/daimontech/dsapi/photos/model/RecommendedPhotos.java
> +
one blank please.

2020-03-14 23:47 UTC, emineayik commented on src/main/java/com/daimontech/dsapi/photos/model/RecommendedPhotos.java
> +import com.daimontech.dsapi.company.model.companyAbout;
fixed

2020-03-14 23:47 UTC, emineayik commented on src/main/java/com/daimontech/dsapi/photos/model/RecommendedPhotos.java
> +
fixed

2020-03-14 23:51 UTC, aykutyurtmen approved these changes

2020-03-15 16:51 UTC, fiiraz requested changes
photos table adı recommended_photos olsa daha iyi olur

2020-03-15 16:51 UTC, fiiraz commented on src/main/java/com/daimontech/dsapi/photos/model/RecommendedPhotos.java
> +@Table(name = "photos")
table adı recommended_photos olsa daha iyi

2020-03-15 18:38 UTC, emineayik commented on src/main/java/com/daimontech/dsapi/photos/model/RecommendedPhotos.java
> +@Table(name = "photos")
fixed

2020-03-15 18:55 UTC, fiiraz approved these changes

2020-03-15 18:55 UTC, merged